baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "DeepLearn :"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "Thoughts about data, AI & innovation "
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Welcome to DeepLearn. A blog about all things data, AI, technology and innovation."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "If you have any comments, questions or queries, please reach out on racheldulberg@gmail.com"
enable = true
title = "Contact me for more information."
[params.footer]
address = ""
content = "A personal blog about all things data, AI & innovation by a data nerd, ex-lawyer and entrepreneur and AI enthusiast based in Melbourne, Australia."
copyright = "Copyright &copy; 2020 Rachel Dulberg"
hours = ""
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
